import { apiJson, getRequestOrigin } from "@/server/mcp-api";

export async function GET(request: Request) {
  const baseUrl = getRequestOrigin(request);

  return apiJson({
    name: "Vibe Code Workspace MCP API",
    kind: "http_json_agent_api",
    baseUrl,
    mcpServer: {
      endpoint: `${baseUrl}/mcp`,
      transport: "streamable_http",
      protocol: "model_context_protocol",
      methods: ["initialize", "ping", "tools/list", "tools/call"],
      tools: [
        "vibe.auth_register",
        "vibe.auth_token",
        "vibe.auth_check",
        "vibe.auth_tokens_revoke",
        "vibe.auth_account_delete",
        "vibe.projects_list",
        "vibe.projects_create",
        "vibe.projects_get",
        "vibe.projects_delete",
        "vibe.feedback_requests_create",
        "vibe.feedback_list",
        "vibe.feedback_assigned_list",
      ],
    },
    transport: {
      type: "https_json",
      contentType: "application/json",
      browserAutomation: false,
      requiredClient: "curl | fetch | HTTP client | MCP wrapper that calls this JSON API",
    },
    browserAutomationPolicy: {
      allowed: false,
      forbiddenTools: [
        "Playwright",
        "Puppeteer",
        "Selenium",
        "browser UI clicking",
        "HTML form submission",
      ],
      instruction:
        "Never use Playwright or browser automation for MCP tasks. Account registration, token issuance, project creation, feedback requests, and feedback reads must use these HTTP JSON endpoints.",
      noHttpClientFallback:
        "If no HTTP request capability is available, stop and ask the user for curl/fetch/API access. Do not fall back to UI automation.",
    },
    auth: {
      type: "bearer",
      header: "Authorization: Bearer <MCP_API_TOKEN>",
      checkEndpoint: "/api/mcp/auth/check",
      publicEndpoints: [
        "GET /api/mcp",
        "GET /api/mcp/schema",
        "POST /api/mcp/auth/register",
        "POST /api/mcp/auth/token",
      ],
      failureShape: {
        error: {
          code: "unauthorized | mcp_api_not_configured | mcp_api_user_not_found",
          message: "string",
          details: "optional object",
        },
      },
    },
    agentProcedure: [
      "If your client supports MCP, configure the server URL as /mcp and call initialize, tools/list, and tools/call.",
      "If your client does not support MCP, use curl, fetch, or an HTTP client against /api/mcp/*.",
      "Do not use Playwright or browser automation.",
      "Read GET /api/mcp or /llms.txt for the short agent contract.",
      "If the user has no MCP token, create an account with vibe.auth_register or POST /api/mcp/auth/register.",
      "If the user has an account, issue a token with vibe.auth_token or POST /api/mcp/auth/token.",
      "Call GET /api/mcp/auth/check with the bearer token before any write.",
      "If authenticated is true, call GET /api/mcp/projects to avoid duplicate project creation.",
      "Create a project with POST /api/mcp/projects only when no existing project matches.",
      "Open a feedback request only after project creation or project lookup succeeds.",
      "Read feedback with GET /api/mcp/feedback?projectId={id}&limit=50.",
    ],
    endpoints: [
      {
        method: "POST",
        path: "/api/mcp/auth/register",
        url: `${baseUrl}/api/mcp/auth/register`,
        description: "Create a local account and return a new MCP API token. No bearer token required.",
        authRequired: false,
        body: {
          email: "string, required",
          handle: "string, required",
          name: "string, optional",
          password: "string, required, 8-128 chars",
        },
      },
      {
        method: "POST",
        path: "/api/mcp/auth/token",
        url: `${baseUrl}/api/mcp/auth/token`,
        description: "Issue a new MCP API token for an existing account using login and password. No bearer token required.",
        authRequired: false,
        body: {
          login: "handle or email",
          password: "string, required",
        },
      },
      {
        method: "GET",
        path: "/api/mcp/auth/check",
        url: `${baseUrl}/api/mcp/auth/check`,
        description: "Validate bearer auth and return the mapped user plus capabilities.",
        authRequired: true,
      },
      {
        method: "GET",
        path: "/api/mcp/me",
        url: `${baseUrl}/api/mcp/me`,
        description: "Return the API user mapped to this token.",
        authRequired: true,
      },
      {
        method: "GET",
        path: "/api/mcp/projects",
        url: `${baseUrl}/api/mcp/projects`,
        description: "List projects owned by the API user.",
        authRequired: true,
      },
      {
        method: "POST",
        path: "/api/mcp/projects",
        url: `${baseUrl}/api/mcp/projects`,
        description: "Create a project.",
        authRequired: true,
        body: {
          title: "string, required",
          summary: "string, required",
          description: "string, optional",
          status: "idea | prototype | building | needs_feedback | iterating | shipped | parked | archived",
          visibility: "private | unlisted | public",
          demoUrl: "url, optional",
          repoUrl: "url, optional",
          tools: "string[], optional",
          feedbackFocus: "feedback_type[], optional",
        },
      },
      {
        method: "GET",
        path: "/api/mcp/projects/{projectId}",
        url: `${baseUrl}/api/mcp/projects/{projectId}`,
        description: "Get one owned project with its feedback requests and received feedback.",
        authRequired: true,
      },
      {
        method: "POST",
        path: "/api/mcp/projects/{projectId}/feedback-requests",
        url: `${baseUrl}/api/mcp/projects/{projectId}/feedback-requests`,
        description: "Open a feedback request for an owned project.",
        authRequired: true,
        body: {
          feedbackTypes: "feedback_type[], default ['first_impression']",
          minFeedbackCount: "number, 1-20, default 1",
          creditCost: "number, 1-20, default minFeedbackCount",
          deadlineDays: "number, 1-30, default 7",
        },
      },
      {
        method: "GET",
        path: "/api/mcp/feedback?projectId=&limit=",
        url: `${baseUrl}/api/mcp/feedback?projectId=&limit=`,
        description: "List feedback received on owned projects.",
        authRequired: true,
      },
      {
        method: "GET",
        path: "/api/mcp/feedback/assigned",
        url: `${baseUrl}/api/mcp/feedback/assigned`,
        description: "List feedback tasks claimed by the API user.",
        authRequired: true,
      },
    ],
    feedbackTypes: [
      "first_impression",
      "ux_ui",
      "bug",
      "mobile_usability",
      "feature_idea",
      "business",
      "code_structure",
      "security_data_risk",
    ],
  });
}
