import { apiJson, getRequestOrigin } from "@/server/mcp-api";

export async function GET(request: Request) {
  const baseUrl = getRequestOrigin(request);

  return apiJson({
    name: "vibearchive MCP API",
    kind: "http_json_agent_api",
    baseUrl,
    mcpServer: {
      endpoint: `${baseUrl}/mcp`,
      transport: "streamable_http",
      protocol: "model_context_protocol",
      methods: ["initialize", "ping", "tools/list", "tools/call"],
      tools: [
        "vibe.auth_register",
        "vibe.auth_token",
        "vibe.auth_check",
        "vibe.auth_tokens_revoke",
        "vibe.auth_account_delete",
        "vibe.projects_list",
        "vibe.projects_create",
        "vibe.projects_get",
        "vibe.projects_claim",
        "vibe.public_projects_list",
        "vibe.public_projects_get",
        "vibe.projects_update",
        "vibe.projects_history",
        "vibe.projects_delete",
        "vibe.feedback_list",
        "vibe.feedback_create",
        "vibe.feedback_update",
        "vibe.feedback_delete",
      ],
    },
    transport: {
      type: "https_json",
      contentType: "application/json",
      browserAutomation: false,
      requiredClient: "curl | fetch | HTTP client | MCP wrapper that calls this JSON API",
    },
    browserAutomationPolicy: {
      allowed: false,
      forbiddenTools: [
        "Playwright",
        "Puppeteer",
        "Selenium",
        "browser UI clicking",
        "HTML form submission",
      ],
      instruction:
        "Never use Playwright or browser automation for MCP tasks. Account registration, token issuance, project CRUD, and feedback comments/private notes must use these HTTP JSON endpoints.",
      noHttpClientFallback:
        "If no HTTP request capability is available, stop and ask the user for curl/fetch/API access. Do not fall back to UI automation.",
    },
    auth: {
      type: "bearer",
      header: "Authorization: Bearer <MCP_API_TOKEN>",
      checkEndpoint: "/api/mcp/auth/check",
      publicEndpoints: [
        "GET /api/mcp",
        "GET /api/mcp/schema",
        "GET /api/mcp/public/projects/list?limit=&offset=&sort=&order=&query=&tag=&tool=",
        "GET /api/mcp/public/projects?projectId= or ?handle=&slug=",
        "POST /api/mcp/auth/register",
        "POST /api/mcp/auth/token",
      ],
      failureShape: {
        error: {
          code: "unauthorized | mcp_api_not_configured | mcp_api_user_not_found",
          message: "string",
          details: "optional object",
        },
      },
    },
    agentProcedure: [
      "If your client supports MCP, configure the server URL as /mcp and call initialize, tools/list, and tools/call.",
      "If your client does not support MCP, use curl, fetch, or an HTTP client against /api/mcp/*.",
      "Do not use Playwright or browser automation.",
      "Read GET /api/mcp or /llms.txt for the short agent contract. /llm.txt redirects to /llms.txt.",
      "List public project posts without login through vibe.public_projects_list or GET /api/mcp/public/projects/list.",
      "Read a public project post without login through vibe.public_projects_get or GET /api/mcp/public/projects?handle={handle}&slug={slug}.",
      "If the user has no account, create one with vibe.auth_register or POST /api/mcp/auth/register. Email is optional and only needed for password recovery after web Settings verification.",
      "Issue a token with vibe.auth_token or POST /api/mcp/auth/token. Email verification is not required.",
      "Call GET /api/mcp/auth/check with the bearer token before any write.",
      "If authenticated is true, call GET /api/mcp/projects to avoid duplicate project creation.",
      "Create a project with POST /api/mcp/projects only when no existing project matches. summary and description support Markdown.",
      "Use projectType=owned for your own projects. Use projectType=external plus sourceUrl/externalOwnerName for public projects you are reviewing or bookmarking.",
      "If a public external project review is actually yours, claim it with vibe.projects_claim or POST /api/mcp/projects/{projectId}/claim. Ownership and edit permissions move to your account.",
      "Provide a screenshot with thumbnailUrl, images[0].url, or thumbnailBase64 plus thumbnailMimeType.",
      "Update or delete owned project posts with PATCH or DELETE /api/mcp/projects/{projectId}.",
      "Read saved project edit history with vibe.projects_history or GET /api/mcp/projects/{projectId}/revisions.",
      "Read received feedback, private self notes, and todos with GET /api/mcp/feedback?projectId={id}&limit=50. Bodies are returned directly.",
      "Create a feedback comment, private note, todo, or reply with POST /api/mcp/feedback. Pass parentFeedbackId for a reply.",
      "Update your own feedback comment content, visibility, or kind with PATCH /api/mcp/feedback. Delete your own comments with DELETE /api/mcp/feedback.",
    ],
    endpoints: [
      {
        method: "POST",
        path: "/api/mcp/auth/register",
        url: `${baseUrl}/api/mcp/auth/register`,
        description:
          "Create a local account. No bearer token required. Email is optional and can be verified later in web Settings for password recovery.",
        authRequired: false,
        body: {
          email: "string, optional",
          handle: "string, required",
          name: "string, optional",
          password: "string, required, 8-128 chars",
        },
      },
      {
        method: "POST",
        path: "/api/mcp/auth/token",
        url: `${baseUrl}/api/mcp/auth/token`,
        description:
          "Issue a new MCP API token using login and password. No bearer token or email verification required.",
        authRequired: false,
        body: {
          login: "handle or email",
          password: "string, required",
        },
      },
      {
        method: "GET",
        path: "/api/mcp/auth/check",
        url: `${baseUrl}/api/mcp/auth/check`,
        description: "Validate bearer auth and return the mapped user plus capabilities.",
        authRequired: true,
      },
      {
        method: "GET",
        path: "/api/mcp/me",
        url: `${baseUrl}/api/mcp/me`,
        description: "Return the API user mapped to this token.",
        authRequired: true,
      },
      {
        method: "GET",
        path: "/api/mcp/projects",
        url: `${baseUrl}/api/mcp/projects`,
        description: "List owned projects and external project reviews managed by the API user.",
        authRequired: true,
      },
      {
        method: "POST",
        path: "/api/mcp/projects",
        url: `${baseUrl}/api/mcp/projects`,
        description: "Create an owned project or external public project review.",
        authRequired: true,
        body: {
          title: "string, required",
          summary: "string, required, Markdown supported",
          description: "string, optional, Markdown supported",
          projectType: "owned | external, default owned",
          externalOwnerName: "string, optional for external",
          externalOwnerUrl: "url, optional for external",
          sourceUrl: "url, required for external unless demoUrl or repoUrl is present",
          status: "idea | prototype | building | needs_feedback | iterating | shipped | parked | archived",
          visibility: "private | unlisted | public",
          demoUrl: "url, optional",
          repoUrl: "url, optional",
          thumbnailUrl: "url, optional screenshot/thumbnail image",
          coverImageUrl: "url, optional alias for thumbnailUrl",
          thumbnailBase64: "base64 image bytes or data URI, optional, max decoded 5MB",
          thumbnailMimeType: "image/jpeg | image/png | image/webp | image/gif, required with raw base64",
          images: "[{ url, alt? }], optional; first URL is used as thumbnail",
          tools: "string[], optional",
          categoryTags: "string[], optional freeform discovery tags",
          feedbackFocus: "feedback_type[], optional",
        },
      },
      {
        method: "GET",
        path: "/api/mcp/projects/{projectId}",
        url: `${baseUrl}/api/mcp/projects/{projectId}`,
        description: "Get one owned project with its received feedback comments.",
        authRequired: true,
      },
      {
        method: "POST",
        path: "/api/mcp/projects/{projectId}/claim",
        url: `${baseUrl}/api/mcp/projects/{projectId}/claim`,
        description:
          "Claim an unclaimed external public project review as the authenticated user's own project. The original submitter remains recorded; ownership and edit permissions move to the claimant.",
        authRequired: true,
      },
      {
        method: "GET",
        path: "/api/mcp/public/projects/list?limit=&offset=&sort=&order=&query=&tag=&tool=",
        url: `${baseUrl}/api/mcp/public/projects/list?limit=50&offset=0`,
        description:
          "List public project posts from the discover board. No bearer token is required. Use projectId, owner.handle, and project.slug from this response with /api/mcp/public/projects for detail.",
        authRequired: false,
        query: {
          limit: "integer 1-100, default 50",
          offset: "integer 0-10000, default 0",
          sort: "updated | title | owner | status | feedback | favorites, default updated",
          order: "asc | desc, optional; defaults desc for updated/feedback/favorites and asc otherwise",
          query: "string, optional full-text-ish contains filter over title, summary, owner, URLs, tags, tools",
          tag: "string, optional exact category tag match",
          tool: "string, optional exact tool match",
        },
      },
      {
        method: "GET",
        path: "/api/mcp/public/projects?projectId=&handle=&slug=",
        url: `${baseUrl}/api/mcp/public/projects?handle={handle}&slug={slug}`,
        description:
          "Get one public project post with public comments only. No bearer token is required. Pass projectId, or pass handle and slug from /p/{handle}/{slug}.",
        authRequired: false,
        query: {
          projectId: "uuid, optional if handle and slug are provided",
          handle: "owner handle from /p/{handle}/{slug}, optional if projectId is provided",
          slug: "project slug from /p/{handle}/{slug}, optional if projectId is provided",
        },
      },
      {
        method: "PATCH",
        path: "/api/mcp/projects/{projectId}",
        url: `${baseUrl}/api/mcp/projects/{projectId}`,
        description: "Update one owned project post. The public slug stays stable.",
        authRequired: true,
        body: {
          title: "string, optional",
          summary: "string, optional, Markdown supported",
          description: "string | null, optional, Markdown supported",
          projectType: "owned | external, optional",
          externalOwnerName: "string | null, optional",
          externalOwnerUrl: "url | null, optional",
          sourceUrl: "url | null, optional",
          status: "idea | prototype | building | needs_feedback | iterating | shipped | parked | archived",
          visibility: "private | unlisted | public",
          demoUrl: "url | null, optional",
          repoUrl: "url | null, optional",
          thumbnailUrl: "url | null, optional",
          coverImageUrl: "url | null, optional alias for thumbnailUrl",
          thumbnailBase64: "base64 image bytes or data URI, optional, max decoded 5MB",
          thumbnailMimeType: "image/jpeg | image/png | image/webp | image/gif, required with raw base64",
          images: "[{ url, alt? }], optional; first URL replaces thumbnail, [] clears it",
          tools: "string[], optional",
          categoryTags: "string[], optional",
          feedbackFocus: "feedback_type[], optional",
        },
      },
      {
        method: "GET",
        path: "/api/mcp/projects/{projectId}/revisions?limit=",
        url: `${baseUrl}/api/mcp/projects/{projectId}/revisions?limit=30`,
        description: "List owner-only saved revision history for one project. Returns prior Markdown descriptions and metadata.",
        authRequired: true,
      },
      {
        method: "DELETE",
        path: "/api/mcp/projects/{projectId}",
        url: `${baseUrl}/api/mcp/projects/{projectId}`,
        description: "Delete one owned project post and its comments.",
        authRequired: true,
      },
      {
        method: "GET",
        path: "/api/mcp/feedback?projectId=&limit=&visibility=&kind=",
        url: `${baseUrl}/api/mcp/feedback?projectId=&limit=&visibility=&kind=`,
        description: "List feedback comments and private notes on owned projects. Bodies are returned directly.",
        authRequired: true,
      },
      {
        method: "POST",
        path: "/api/mcp/feedback",
        url: `${baseUrl}/api/mcp/feedback`,
        description: "Create a feedback comment on a visible project. Use parentFeedbackId to create a reply.",
        authRequired: true,
        body: {
          projectId: "uuid, required",
          parentFeedbackId: "uuid, optional",
          body: "string, required, max 2000 chars",
          feedbackType: "feedback_type, optional",
          rating: "integer 1-5, optional",
          visibility: "public | private, optional",
          kind: "feedback | self_note | todo | decision | update | release, optional",
        },
      },
      {
        method: "PATCH",
        path: "/api/mcp/feedback",
        url: `${baseUrl}/api/mcp/feedback`,
        description: "Update your own comment content, visibility, or kind.",
        authRequired: true,
        body: {
          feedbackId: "uuid, required",
          body: "string, optional, max 2000 chars",
          feedbackType: "feedback_type, optional",
          rating: "integer 1-5, optional",
          visibility: "public | private, optional",
          kind: "feedback | self_note | todo | decision | update | release, optional",
        },
      },
      {
        method: "DELETE",
        path: "/api/mcp/feedback",
        url: `${baseUrl}/api/mcp/feedback`,
        description: "Delete one feedback comment authored by the authenticated user.",
        authRequired: true,
        body: {
          feedbackId: "uuid, required",
        },
      },
    ],
    feedbackVisibilities: ["public", "private"],
    feedbackKinds: ["feedback", "self_note", "todo", "decision", "update", "release"],
    feedbackTypes: [
      "first_impression",
      "ux_ui",
      "bug",
      "mobile_usability",
      "feature_idea",
      "business",
      "code_structure",
      "security_data_risk",
    ],
  });
}
